

--Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(purhcase_amount) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    gender,
    category,
    purhcase_amount,
    discount_applied
FROM customer
WHERE discount_applied = 'Yes'
  AND purhcase_amount > (
      SELECT AVG(purhcase_amount)
      FROM customer
  )
ORDER BY purhcase_amount DESC;

--Q3. What are the top 5 products based on their average customer rating?
SELECT 
    item_purchased,
    ROU(AVG(review_rating), 2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;
